# Generated by Django 4.1.7 on 2023-05-21 18:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LOAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenloai', models.CharField(default='Vui lòng nhập tên loại!', max_length=100, unique=True)),
                ('mota', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NHACUNGCAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tennhacungcap', models.CharField(default='Vui lòng nhập tên nhà cung cấp!', max_length=100, unique=True)),
                ('diachi', models.CharField(max_length=100)),
                ('email', models.EmailField(default='nhacungcap@email.com', max_length=254)),
                ('sodienthoai', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PHONG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenphong', models.CharField(default='Vui lòng nhập tên phòng!', max_length=100, unique=True)),
                ('sotang', models.IntegerField(default=0)),
                ('mota', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='THIETBI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenthietbi', models.CharField(default='Vui lòng nhập tên thiết bị!', max_length=100, unique=True)),
                ('giamua', models.IntegerField(default=0)),
                ('ngaythem', models.DateTimeField(default=datetime.datetime(2023, 5, 22, 1, 28, 18, 338607))),
                ('ngaysanxuat', models.DateTimeField(default=datetime.datetime(2023, 5, 22, 1, 28, 18, 338607))),
                ('ngaymua', models.DateTimeField(default=datetime.datetime(2023, 5, 22, 1, 28, 18, 338607))),
                ('ngayhethanbaohanh', models.DateTimeField(default=datetime.datetime(2023, 5, 22, 1, 28, 18, 338607))),
                ('ngaykiemtradinhky', models.DateTimeField(default=datetime.datetime(2023, 5, 22, 1, 28, 18, 338607))),
                ('tinhtrang', models.CharField(choices=[('tinhtrang1', 'Bình thường'), ('tinhtrang2', 'Đang hỏng'), ('tinhtrang3', 'Đang sửa'), ('tinhtrang4', 'Hết hạn bảo hành'), ('tinhtrang5', 'Đến hạn kiểm tra định kỳ')], default='tinhtrang1', max_length=255)),
                ('mota', models.TextField(blank=True, default='', null=True)),
                ('tenloai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thietbi.loai')),
                ('tennhacungcap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thietbi.nhacungcap')),
                ('tenphong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thietbi.phong')),
            ],
        ),
    ]
