# Generated by Django 4.1.7 on 2023-05-22 03:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thietbi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhacungcap',
            name='mota',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='loai',
            name='tenloai',
            field=models.CharField(default='Chưa xác định tên loại!', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='nhacungcap',
            name='diachi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nhacungcap',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='nhacungcap',
            name='sodienthoai',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='nhacungcap',
            name='tennhacungcap',
            field=models.CharField(default='Chưa xác định tên nhà cung cấp!', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='phong',
            name='tenphong',
            field=models.CharField(default='Chưa xác định tên phòng!', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='thietbi',
            name='ngayhethanbaohanh',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 10, 6, 15, 640379)),
        ),
        migrations.AlterField(
            model_name='thietbi',
            name='ngaykiemtradinhky',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 10, 6, 15, 640379)),
        ),
        migrations.AlterField(
            model_name='thietbi',
            name='ngaymua',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 10, 6, 15, 640379)),
        ),
        migrations.AlterField(
            model_name='thietbi',
            name='ngaysanxuat',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 10, 6, 15, 640379)),
        ),
        migrations.AlterField(
            model_name='thietbi',
            name='ngaythem',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 10, 6, 15, 640379)),
        ),
        migrations.AlterField(
            model_name='thietbi',
            name='tenthietbi',
            field=models.CharField(default='Chưa xác định tên thiết bị!', max_length=100, unique=True),
        ),
    ]
