# Generated by Django 4.1.7 on 2023-05-22 03:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thietbi', '0002_nhacungcap_mota_alter_loai_tenloai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhacungcap',
            name='diachi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nhacungcap',
            name='email',
            field=models.EmailField(blank=True, default='example@email.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='nhacungcap',
            name='sodienthoai',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='thietbi',
            name='ngayhethanbaohanh',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 10, 21, 59, 535166)),
        ),
        migrations.AlterField(
            model_name='thietbi',
            name='ngaykiemtradinhky',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 10, 21, 59, 535166)),
        ),
        migrations.AlterField(
            model_name='thietbi',
            name='ngaymua',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 10, 21, 59, 535166)),
        ),
        migrations.AlterField(
            model_name='thietbi',
            name='ngaysanxuat',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 10, 21, 59, 535166)),
        ),
        migrations.AlterField(
            model_name='thietbi',
            name='ngaythem',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 10, 21, 59, 535166)),
        ),
    ]
