# Generated by Django 4.1.7 on 2023-05-22 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thietbi', '0003_alter_nhacungcap_diachi_alter_nhacungcap_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thietbi',
            name='ngayhethanbaohanh',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 17, 35, 40, 991422)),
        ),
        migrations.AlterField(
            model_name='thietbi',
            name='ngaykiemtradinhky',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 17, 35, 40, 991422)),
        ),
        migrations.AlterField(
            model_name='thietbi',
            name='ngaymua',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 17, 35, 40, 991422)),
        ),
        migrations.AlterField(
            model_name='thietbi',
            name='ngaysanxuat',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 17, 35, 40, 991422)),
        ),
        migrations.AlterField(
            model_name='thietbi',
            name='ngaythem',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 17, 35, 40, 991422)),
        ),
        migrations.AlterField(
            model_name='thietbi',
            name='tinhtrang',
            field=models.CharField(choices=[('tinhtrang1', 'Bình thường'), ('tinhtrang2', 'Đang hỏng'), ('tinhtrang3', 'Đang sửa')], default='tinhtrang1', max_length=255),
        ),
    ]
