# Generated by Django 4.1.7 on 2023-05-22 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thietbi', '0004_alter_thietbi_ngayhethanbaohanh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thietbi',
            name='ngayhethanbaohanh',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='thietbi',
            name='ngaykiemtradinhky',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='thietbi',
            name='ngaymua',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='thietbi',
            name='ngaysanxuat',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='thietbi',
            name='ngaythem',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
