# Generated by Django 4.1.7 on 2023-05-22 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thietbi', '0005_alter_thietbi_ngayhethanbaohanh_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thietbi',
            name='ngaysanxuat',
        ),
        migrations.AlterField(
            model_name='thietbi',
            name='ngayhethanbaohanh',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 17, 46, 2, 146048)),
        ),
        migrations.AlterField(
            model_name='thietbi',
            name='ngaykiemtradinhky',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 17, 46, 2, 146048)),
        ),
        migrations.AlterField(
            model_name='thietbi',
            name='ngaymua',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 17, 46, 2, 146048)),
        ),
        migrations.AlterField(
            model_name='thietbi',
            name='ngaythem',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
