# Generated by Django 4.1.7 on 2023-05-22 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thietbi', '0007_alter_thietbi_ngayhethanbaohanh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thietbi',
            name='ngayhethanbaohanh',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 19, 58, 4, 65098)),
        ),
        migrations.AlterField(
            model_name='thietbi',
            name='ngaykiemtradinhky',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 19, 58, 4, 65098)),
        ),
        migrations.AlterField(
            model_name='thietbi',
            name='ngaymua',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 19, 58, 4, 65098)),
        ),
    ]
