# Generated by Django 4.1.7 on 2023-05-22 13:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thietbi', '0010_alter_thietbi_ngayhethanbaohanh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thietbi',
            name='ngayhethanbaohanh',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 20, 28, 6, 536810)),
        ),
        migrations.AlterField(
            model_name='thietbi',
            name='ngaykiemtradinhky',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 20, 28, 6, 536810)),
        ),
        migrations.AlterField(
            model_name='thietbi',
            name='ngaymua',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 20, 28, 6, 536810)),
        ),
        migrations.AlterField(
            model_name='thietbi',
            name='nguoi_dung',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
