# Generated by Django 4.1.7 on 2023-05-23 19:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thietbi', '0011_alter_thietbi_ngayhethanbaohanh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loai',
            name='nguoi_dung',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nhacungcap',
            name='nguoi_dung',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phong',
            name='nguoi_dung',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thietbi',
            name='ngayhethanbaohanh',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 2, 54, 28, 108063)),
        ),
        migrations.AlterField(
            model_name='thietbi',
            name='ngaykiemtradinhky',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 2, 54, 28, 108063)),
        ),
        migrations.AlterField(
            model_name='thietbi',
            name='ngaymua',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 2, 54, 28, 108063)),
        ),
    ]
