# Generated by Django 4.1.7 on 2023-05-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguoidung',
            name='tendangnhap',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
