# Generated by Django 4.1.7 on 2023-05-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_nguoidung_tendangnhap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nguoidung',
            name='matkhau',
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='email',
            field=models.EmailField(default='you default value or example@email.com', max_length=254),
        ),
    ]
