# Generated by Django 4.1.7 on 2023-05-22 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_nguoidung_diachi_nguoidung_gioitinh_nguoidung_hoten_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguoidung',
            name='diachi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='hoten',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='ngaysinh',
            field=models.DateField(default=datetime.datetime(2023, 5, 22, 19, 58, 4, 65098)),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
